services:
    nbrb_exchange_rates.api_client:
        class: Submarine\NbrbExchangeRatesBundle\Client\ApiClient
        arguments:
            - '%submarine_nbrb_exchange_rates.source.url_exchange_rates%'
            - '%submarine_nbrb_exchange_rates.source.url_exchange_rates_dynamic%'
            - '%submarine_nbrb_exchange_rates.source.connect_timeout%'
            - '%submarine_nbrb_exchange_rates.source.timeout%'


    nbrb_exchange_rates.provider:
        class: Submarine\NbrbExchangeRatesBundle\Provider\ExchangeRatesProvider
        arguments:
            - '@nbrb_exchange_rates.api_client'




    nbrb_exchange_rates.cacher:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ['%submarine_nbrb_exchange_rates.cache.dir%']